import os
from pathlib import Path

from sqlalchemy import create_engine, inspect, text
from sqlalchemy.orm import DeclarativeBase, sessionmaker


DATA_DIR = Path(os.getenv("TURNOS_DATA_DIR", ".")).resolve()
DATA_DIR.mkdir(parents=True, exist_ok=True)
DATABASE_URL = f"sqlite:///{(DATA_DIR / 'turnos_historial.db').as_posix()}"

engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False},
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


class Base(DeclarativeBase):
    pass


def init_db():
    Base.metadata.create_all(bind=engine)

    with engine.begin() as connection:
        inspector = inspect(connection)
        table_names = set(inspector.get_table_names())

        patient_columns = {column["name"] for column in inspector.get_columns("patients")}
        if "prescribed_sessions" not in patient_columns:
            connection.execute(
                text("ALTER TABLE patients ADD COLUMN prescribed_sessions INTEGER NOT NULL DEFAULT 0")
            )
        if "photo_filename" not in patient_columns:
            connection.execute(text("ALTER TABLE patients ADD COLUMN photo_filename VARCHAR(255)"))
        if "care_mode" not in patient_columns:
            connection.execute(
                text("ALTER TABLE patients ADD COLUMN care_mode VARCHAR(20) NOT NULL DEFAULT 'institutional'")
            )
        if "treatment_start_date" not in patient_columns:
            connection.execute(text("ALTER TABLE patients ADD COLUMN treatment_start_date DATE"))
        if "billing_month" not in patient_columns:
            connection.execute(text("ALTER TABLE patients ADD COLUMN billing_month DATE"))
        if "session_price" not in patient_columns:
            connection.execute(text("ALTER TABLE patients ADD COLUMN session_price INTEGER NOT NULL DEFAULT 0"))
        if "preferred_time" not in patient_columns:
            connection.execute(text("ALTER TABLE patients ADD COLUMN preferred_time TIME"))
        if "preferred_weekdays" not in patient_columns:
            connection.execute(text("ALTER TABLE patients ADD COLUMN preferred_weekdays VARCHAR(32)"))
        if "auto_schedule_enabled" not in patient_columns:
            connection.execute(text("ALTER TABLE patients ADD COLUMN auto_schedule_enabled BOOLEAN NOT NULL DEFAULT 0"))

        appointment_columns = {column["name"] for column in inspector.get_columns("appointments")}
        if "autogenerated" not in appointment_columns:
            connection.execute(text("ALTER TABLE appointments ADD COLUMN autogenerated BOOLEAN NOT NULL DEFAULT 0"))
        if "manual_override" not in appointment_columns:
            connection.execute(text("ALTER TABLE appointments ADD COLUMN manual_override BOOLEAN NOT NULL DEFAULT 0"))
        if "session_number" not in appointment_columns:
            connection.execute(text("ALTER TABLE appointments ADD COLUMN session_number INTEGER"))

        if "users" not in table_names:
            Base.metadata.create_all(bind=engine)
        else:
            user_columns = {column["name"] for column in inspector.get_columns("users")}
            if "phone" not in user_columns:
                connection.execute(text("ALTER TABLE users ADD COLUMN phone VARCHAR(40)"))
            if "institutional_rate" not in user_columns:
                connection.execute(text("ALTER TABLE users ADD COLUMN institutional_rate INTEGER NOT NULL DEFAULT 0"))
            if "domiciliary_rate" not in user_columns:
                connection.execute(text("ALTER TABLE users ADD COLUMN domiciliary_rate INTEGER NOT NULL DEFAULT 0"))


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
