from datetime import date, datetime, time

from sqlalchemy import Boolean, Date, DateTime, ForeignKey, Integer, String, Text, Time
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .database import Base


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    username: Mapped[str] = mapped_column(String(60), unique=True, index=True)
    full_name: Mapped[str] = mapped_column(String(120))
    phone: Mapped[str | None] = mapped_column(String(40), default=None)
    password_hash: Mapped[str] = mapped_column(String(256))
    recovery_code_hash: Mapped[str] = mapped_column(String(256))
    session_token_hash: Mapped[str | None] = mapped_column(String(256), default=None)
    institutional_rate: Mapped[int] = mapped_column(Integer, default=0)
    domiciliary_rate: Mapped[int] = mapped_column(Integer, default=0)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)


class Patient(Base):
    __tablename__ = "patients"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    full_name: Mapped[str] = mapped_column(String(120), index=True)
    photo_filename: Mapped[str | None] = mapped_column(String(255), default=None)
    phone: Mapped[str | None] = mapped_column(String(40), default=None)
    email: Mapped[str | None] = mapped_column(String(120), default=None)
    diagnosis: Mapped[str | None] = mapped_column(String(160), default=None)
    notes: Mapped[str | None] = mapped_column(Text, default=None)
    care_mode: Mapped[str] = mapped_column(String(20), default="institutional")
    prescribed_sessions: Mapped[int] = mapped_column(default=0)
    treatment_start_date: Mapped[date | None] = mapped_column(Date, default=None)
    billing_month: Mapped[date | None] = mapped_column(Date, default=None)
    session_price: Mapped[int] = mapped_column(Integer, default=0)
    preferred_time: Mapped[time | None] = mapped_column(Time, default=None)
    preferred_weekdays: Mapped[str | None] = mapped_column(String(32), default=None)
    auto_schedule_enabled: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    appointments: Mapped[list["Appointment"]] = relationship(
        back_populates="patient",
        cascade="all, delete-orphan",
        order_by="Appointment.date.desc()",
    )

    def weekday_values(self) -> list[int]:
        if not self.preferred_weekdays:
            return []
        return [int(value) for value in self.preferred_weekdays.split(",") if value != ""]

    @property
    def completed_sessions(self) -> int:
        return sum(1 for appointment in self.appointments if appointment.status == "completed")

    @property
    def remaining_sessions(self) -> int:
        return max(self.prescribed_sessions - self.completed_sessions, 0)

    @property
    def photo_url(self) -> str | None:
        if not self.photo_filename:
            return None
        return f"/patient-photos/{self.photo_filename}"

    @property
    def projected_revenue(self) -> int:
        return self.session_price * self.prescribed_sessions

    @property
    def treatment_end_date(self) -> date | None:
        relevant_dates = [
            appointment.date
            for appointment in self.appointments
            if appointment.status != "cancelled"
        ]
        if not relevant_dates:
            return None
        return max(relevant_dates)


class Appointment(Base):
    __tablename__ = "appointments"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    patient_id: Mapped[int] = mapped_column(ForeignKey("patients.id"), index=True)
    date: Mapped[date] = mapped_column(Date, index=True)
    time: Mapped[time] = mapped_column(Time, index=True)
    duration_minutes: Mapped[int] = mapped_column(default=60)
    status: Mapped[str] = mapped_column(String(20), default="scheduled")
    reason: Mapped[str | None] = mapped_column(String(160), default=None)
    evolution_note: Mapped[str | None] = mapped_column(Text, default=None)
    autogenerated: Mapped[bool] = mapped_column(Boolean, default=False)
    manual_override: Mapped[bool] = mapped_column(Boolean, default=False)
    session_number: Mapped[int | None] = mapped_column(Integer, default=None)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    patient: Mapped["Patient"] = relationship(back_populates="appointments")


class Holiday(Base):
    __tablename__ = "holidays"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    date: Mapped[date] = mapped_column(Date, unique=True, index=True)
    name: Mapped[str | None] = mapped_column(String(120), default=None)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
