from datetime import date as dt_date, datetime as dt_datetime, time as dt_time
from typing import Literal, Optional

from pydantic import BaseModel, ConfigDict, EmailStr, Field, field_validator


AppointmentStatus = Literal["scheduled", "completed", "cancelled"]
CareMode = Literal["institutional", "domiciliary"]


class PatientBase(BaseModel):
    full_name: str = Field(min_length=2, max_length=120)
    phone: str | None = Field(default=None, max_length=40)
    email: EmailStr | None = None
    diagnosis: str | None = Field(default=None, max_length=160)
    notes: str | None = None
    care_mode: CareMode = "institutional"
    prescribed_sessions: int = Field(default=0, ge=0, le=120)
    treatment_start_date: dt_date | None = None
    billing_month: dt_date | None = None
    session_price: int = Field(default=0, ge=0, le=1_000_000)
    preferred_time: dt_time | None = None
    preferred_weekdays: list[int] = Field(default_factory=list)
    auto_schedule_enabled: bool = False

    @field_validator("preferred_weekdays", mode="before")
    @classmethod
    def parse_preferred_weekdays(cls, value):
        if value is None or value == "":
            return []
        if isinstance(value, str):
            return [int(chunk) for chunk in value.split(",") if chunk != ""]
        return value


class PatientCreate(PatientBase):
    pass


class PatientUpdate(BaseModel):
    full_name: str | None = Field(default=None, min_length=2, max_length=120)
    phone: str | None = Field(default=None, max_length=40)
    email: EmailStr | None = None
    diagnosis: str | None = Field(default=None, max_length=160)
    notes: str | None = None
    care_mode: CareMode | None = None
    prescribed_sessions: int | None = Field(default=None, ge=0, le=120)
    treatment_start_date: dt_date | None = None
    billing_month: dt_date | None = None
    session_price: int | None = Field(default=None, ge=0, le=1_000_000)
    preferred_time: dt_time | None = None
    preferred_weekdays: list[int] | None = None
    auto_schedule_enabled: bool | None = None

    @field_validator("preferred_weekdays", mode="before")
    @classmethod
    def parse_update_preferred_weekdays(cls, value):
        if value is None or value == "":
            return value
        if isinstance(value, str):
            return [int(chunk) for chunk in value.split(",") if chunk != ""]
        return value


class PatientRead(PatientBase):
    model_config = ConfigDict(from_attributes=True)

    id: int
    created_at: dt_datetime
    photo_url: str | None = None
    completed_sessions: int
    remaining_sessions: int
    projected_revenue: int
    treatment_end_date: dt_date | None = None


class AppointmentBase(BaseModel):
    patient_id: int
    date: dt_date
    time: dt_time
    duration_minutes: int = Field(default=60, ge=30, le=120)
    status: AppointmentStatus = "scheduled"
    reason: str | None = Field(default=None, max_length=160)
    evolution_note: str | None = None


class AppointmentCreate(AppointmentBase):
    pass


class AppointmentUpdate(BaseModel):
    patient_id: Optional[int] = None
    date: Optional[dt_date] = None
    time: Optional[dt_time] = None
    duration_minutes: Optional[int] = Field(default=None, ge=30, le=120)
    status: Optional[AppointmentStatus] = None
    reason: Optional[str] = Field(default=None, max_length=160)
    evolution_note: Optional[str] = None


class AppointmentRead(AppointmentBase):
    model_config = ConfigDict(from_attributes=True)

    id: int
    created_at: dt_datetime
    autogenerated: bool
    manual_override: bool
    session_number: int | None = None
    patient: PatientRead


class DashboardSummary(BaseModel):
    total_patients: int
    upcoming_appointments: int
    completed_sessions: int
    today_label: str
    current_month_new_patients: int
    monthly_patient_limit: int
    current_month_projected_revenue: int


class PricingSettingsRead(BaseModel):
    institutional_rate: int
    domiciliary_rate: int


class PricingSettingsUpdate(BaseModel):
    institutional_rate: int = Field(ge=0, le=1_000_000)
    domiciliary_rate: int = Field(ge=0, le=1_000_000)


class PricingBulkApplyRequest(BaseModel):
    amount: int = Field(ge=0, le=1_000_000)
    scope: Literal["all", "institutional", "domiciliary"] = "all"


class AuthStatus(BaseModel):
    configured: bool
    authenticated: bool
    username: str | None = None
    full_name: str | None = None
    has_recovery_phone: bool = False


class SetupRequest(BaseModel):
    username: str = Field(min_length=3, max_length=60)
    full_name: str = Field(min_length=2, max_length=120)
    password: str = Field(min_length=4, max_length=120)
    phone: str | None = Field(default=None, max_length=40)


class LoginRequest(BaseModel):
    username: str = Field(min_length=3, max_length=60)
    password: str = Field(min_length=4, max_length=120)


class RecoverRequest(BaseModel):
    username: str = Field(min_length=3, max_length=60)
    recovery_code: str = Field(min_length=6, max_length=64)
    new_password: str = Field(min_length=4, max_length=120)


class RecoveryCodeRequest(BaseModel):
    username: str = Field(min_length=3, max_length=60)
    phone: str | None = Field(default=None, max_length=40)


class RecoveryCodeResponse(BaseModel):
    recovery_code: str
    phone: str


class AuthResponse(BaseModel):
    token: str
    username: str
    full_name: str
    recovery_code: str | None = None


class HolidayCreate(BaseModel):
    date: dt_date
    name: str | None = Field(default=None, max_length=120)


class HolidayRead(HolidayCreate):
    model_config = ConfigDict(from_attributes=True)

    id: int
    created_at: dt_datetime
